---
# defaults file for roles/jenkins
jenkins_user: jenkins
jenkins_version: latest
jenkins_download_url: "http://mirrors.jenkins.io/war/{{ jenkins_version }}/jenkins.war"
jenkins_home: "/opt/jenkins/{{ jenkins_version }}/"
JAVA_OPTS: "-Djava.awt.headless=true -DJENKINS_HOME={{ jenkins_home }}"