- hosts: localhost
  vars:
    accounts:
    - { name: Identity,  id: 818440412345 }
    - { name: Devops,    id: 794873312345 }
    - { name: WCA,       id: 544564512345 }
    - { name: API,       id: 394936412345 }

  tasks:
  - debug:
      msg: "{{ accounts|search_id }}"
