- hosts: appserver
  tasks:
  - name:
    checker:
      process: java
      user: jenkins
      url: http://192.168.1.71:8080/login?from=%2F
      regex_str: 'Getting Started'
      regex_str_srv: 'X-Jenkins:'
    become: yes
    register: output

  - debug:
      var: output