- name: load local facts about server
  setup:
    filter: ansible_local

- include_tasks: jenkins_configuration.yml
#  when: ansible_local.jenkins is not defined or ansible_local.jenkins.jenkins_configured != 'True'